[vendor]
name = "The Infinity's"
id = "org.infinite"
url = "https://github.com/The-Infinitys/metal-xross"
au_manufacturer = "INFI"  # 厳密に4文字

[[plugin]]
name = "MetalXross"
bundle_id = "metalxross"   # ハイフンなし推奨と書いてあります
crate = "metal-xross"      # Cargoの実際の名前
category = "effect"        # これを "effect" にすることでMIDIを排除しやすくする
fourcc = "MXRS"            # 厳密に4文字
au_tag = "Effects"
