[vendor]
name = "The Infinity's"
id = "org.infinite"
url = "https://github.com/The-Infinitys/metal-xross"
au_manufacturer = "Infinity"

[[plugin]]
name = "MetalXross"
bundle_id = "metal-xross"
crate = "metal-xross"
category = "effect"
fourcc = "MXro"
au_tag = "Effects"
